### ISSUE TITLE
Bug: Image upload does not correctly hash the message body

### ISSUE THREAD

**Issue by nomeez** [rokka-io/rokka-client-php-cli#7] opened 2016-07-25 12:21 UTC
Hi

When uploading an image with the php cli, the message body's hash is not correctly included in the Api-Signature. In fact the body's hash is always sha1("").

Base.php getEncodedBodyData() seems to return ("") for multipart messages.

I was trying to implement a java client for the image upload functionality. Which never worked when I accidently found out I could upload any image using the same signature, wich was generated with sha1("") as the body hash.
This might be a system wide issue, as it seems to be implemented wrong on the client and the backend side.

**Comment by thePanz** [comment] 2016-11-15 12:14
Thanks @nomeez for reporting this issue, as you mentioned this is not a bug from the CLI, but from the Rokka Client library.
The issues should be fixed by https://github.com/rokka-io/rokka-client-php/pull/10

Please, create a new issue if you have this problem

**Closed as completed by thePanz** 2016-11-15 12:14 UTC
